// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeT6CvXLXmHZzvgBwgjCXq0VOTiVPMV8w',
    appId: '1:986955898654:web:bf08a6106deb0dc62c730f',
    messagingSenderId: '986955898654',
    projectId: 'rehabunified-task-1234',
    authDomain: 'rehabunified-task-1234.firebaseapp.com',
    storageBucket: 'rehabunified-task-1234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxJ7lYgSUJBUW325BHxiaQbdO4WcxxKTI',
    appId: '1:986955898654:android:83b94fdbae660c6c2c730f',
    messagingSenderId: '986955898654',
    projectId: 'rehabunified-task-1234',
    storageBucket: 'rehabunified-task-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmgv6g0sbXIleWNqiw3SPLodnt6YuiF2o',
    appId: '1:986955898654:ios:d1f18bea8996d3af2c730f',
    messagingSenderId: '986955898654',
    projectId: 'rehabunified-task-1234',
    storageBucket: 'rehabunified-task-1234.firebasestorage.app',
    iosBundleId: 'com.example.rehabunifiedTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmgv6g0sbXIleWNqiw3SPLodnt6YuiF2o',
    appId: '1:986955898654:ios:d1f18bea8996d3af2c730f',
    messagingSenderId: '986955898654',
    projectId: 'rehabunified-task-1234',
    storageBucket: 'rehabunified-task-1234.firebasestorage.app',
    iosBundleId: 'com.example.rehabunifiedTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeT6CvXLXmHZzvgBwgjCXq0VOTiVPMV8w',
    appId: '1:986955898654:web:16ae6161ec62edd32c730f',
    messagingSenderId: '986955898654',
    projectId: 'rehabunified-task-1234',
    authDomain: 'rehabunified-task-1234.firebaseapp.com',
    storageBucket: 'rehabunified-task-1234.firebasestorage.app',
  );
}
